### ISSUE TITLE
Uninstalled itself

### ISSUE THREAD

**Issue by kevintloney** [tgienger/Ultimate-Crosshair#9]
It uninstalled itself from overwolf and it won't install now. I press ok on install and nothing happens. The window just closes!

**Comment by Myrran** [comment]
Ultimate Crosshair just disappeared. When I try to install it again, nothing happens.

**Comment by tgienger** [comment]
I'll have a look this weekend.

**Comment by ayushty2** [comment]
I tried downloading it recently aswell, i think overwolf has disabled the use of it. Is there any way to bypass this?

**Comment by tgienger** [comment]
I've updated it so it works again. It seems they've blocked apps with a reference to "crosshair" in either the name or description so if this problem arises try changing the name in the  manifest.json file and message me here again so I can update it. 

Anything else?

**Comment by ayushty2** [comment]
Thanks, its working beautifully now

**Comment by LEOkonami** [comment]
Hey there!

My name is Or Manor from the Overwolf support team, 

I just wanted to let you know that all apps that are not available directly from app store like the app you mentioned are not created by Overwolf devs. It means that we do not support these apps and have no control over them -- they could be potentially dangerous.

For this reason, all 3rd party apps have been blocked from our platform and will not work anymore. Please also note that using these apps could cause you a ban on both the Overwolf platform and the game you are playing.

Please play safe, 
Or (LEOkonami) Manor

**Comment by tgienger** [comment]
@LEOkonami I think it's in your teams best interest not to try to partake in some war against 3rd party apps, or at the very least don't reject applications like this one. Did you know that there are apps in your store that allow for crosshairs to be placed in any game? Did you choose to discriminate against my application because I didn't try to mask it or is there some other reason you wont share on here?

**Comment by Fleades** [comment]
Hey @tgienger, my name is Uri and I'm CEO at Overwolf.  First - thanks for your feedback and comments, and for you passion about contributing to the community. We started this company wanting to bring value to every gamer in every game... and we'd love to work together with you on making it happen on this front too. 

Our issue here is that your app was used for Fortnite, and Epic Games reached out to us and told us to remove it - since they consider it cheating. Since we want to keep Overwolf neutral, we're not interested in going against the game publishers and this is why we had to disable the crosshair apps. 

How do you think we can solve this issue? What would you do instead of us?

**Comment by kevintloney** [comment]
I'd love to assist in solving this issue. Thank you for reaching out with
the community on this issue. Nonetheless, individual apps can be enabled or
disabled for specific games in the Overwolf library. I recently have seen
this with the app 'CS:GO Scout.' When installed, it only can be enabled on
CS:GO. As I can't see the inner workings of the program, I can only infer.
Is there a way to target Ultimate Crosshair specifically with agreement
alongside @tgienger (its developer), such that it hooks on every game in
the library besides those where external crosshairs are considered
cheating? If you have any feedback you'd like to offer or if you found this
message useful in some capacity please let me know with a reply below.

**Comment by Fleades** [comment]
Hey @kevlooney (@tgienger ), thanks for your note! That's actually a great idea... there is a way for the developer to allow this app for some games, and prevent it from others. @tgienger will you be interested in adding such a mechanism? that we we'd be able to publish it on the Overwolf store

**Comment by tgienger** [comment]
Being a game developer myself I fully understand the desire and _need_ to keep things fair between players. However in my experience a crosshair falls into the category of something that all players have access to and should have the option of using because let's face it all you need to do is dab a dot on your screen and no one can detect you're using one. Trying to use a fading or moving crosshair is a dated mechanic that players will find a way around that is not punishable so punishing those that do use something like this is even more unfair than using it to begin with.

With that said, it is up to the game developers discretion to allow the use of third party apps. @Fleades I do believe this is the most fair solution. Then it's up to the players of the game to convince the game developers that it's fair use. The only question I have is how to make this process simple across all applications and games? The developer of the app manually adding in allowed games to the manifest doesn't sound like a solid solution since you would have to send in an updated version every time a game is added and there are likely more games that would allow a crosshair than not its going to build up fast. Perhaps you @Fleades (Overwolf) has or could have a database that applications check when they are started and online. Then no updates are necessary and any time a developer contacts you about removing a specific type of application it's as simple as adding that game to the list of flagged games.

**Comment by Fleades** [comment]
hey @tgienger  this sounds like a good solution! If we'd build this list, will you be able to develop support for it?

**Comment by tgienger** [comment]
@Fleades Of course. If you would like I can join up in slack to continue this discussion? If so tgienger on there.

**Comment by Fleades** [comment]
Yes! Please email me to uri dot marchand at overwolf dot com and I will add you! @tgienger
